### ISSUE TITLE
Checkpoint 1 Ready

### ISSUE THREAD

**Issue by GlynisF** [GlynisF/MidwestEventTracker#1]
@pawaitemadisoncollege good to go!

**Comment by pawaitemadisoncollege** [comment]
Hi @GlynisF!

**Problem Statement** Clearly describes the problem and the solution! 

- [ ] This would  be improved: _Midwest Event Tracker is here to help smaller promoters elevate their event game._ by adding the acronym so it's clear what it means in the next sentence.  _Midwest Event Tracker (MET) is here to help smaller promoters elevate their event game._ 
- [ ] It would help those reviewing your repository to understand more about your project if the version numbers of the various tech were included: which hibernate version, which log4j version, etc.

**Project Plan** the first weeks do a good job detailing out work to be done and it appears you are checking off completed items. 

- [ ] Next steps- detail out the remaining 8 weeks. There is a lot to do and it will be critical to have a solid plan. 
- [ ] I recommend adding the details for each user story to the plan: many will need: entity, tests, jsps, servlet, etc.

**Screens** Looks like a good start with these. I generally like to compare the user stories to the screens to make sure all MVP (minimum viable product) stories are covered, so I'll provide more here once I locate the user stories.

- [ ] I noticed a lot of screens for user sign up, sign in, etc.  We'll be using Amazon Cognito for this, so you may want to do this work _after_ completing the week 7 exercise. 

**User Stories**

Can you point me to these so that I can understand the scope of the project and verify it meets the goals of the ent java indie project? Sorry if I overlooked this! 

**Other things:**

- [ ] I noticed an odd directory in your project. I wonder if maybe this was an artifact of working on the log4j config. Is logging working ok?
![Screenshot 2023-10-15 at 11 15 17 AM](https://github.com/GlynisF/MidwestEventTracker/assets/13874466/58409b31-c03f-47e9-a5d6-a2eab42f1306)
